H2H = {'api': {'fixtures': [{'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2010-08-23T20:00:00+01:00',
                       'event_timestamp': 1282590000,
                       'firstHalfStart': None,
                       'fixture_id': 194566,
                       'goalsAwayTeam': 0,
                       'goalsHomeTeam': 3,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 701,
                       'referee': None,
                       'round': 'Regular Season - 37',
                       'score': {'extratime': None,
                                 'fulltime': '3-0',
                                 'halftime': '1-0',
                                 'penalty': None},
                       'secondHalfStart': None,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Etihad Stadium, Manchester (Manchester)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 90,
                       'event_date': '2011-04-11T20:00:00+01:00',
                       'event_timestamp': 1302548400,
                       'firstHalfStart': None,
                       'fixture_id': 194264,
                       'goalsAwayTeam': 0,
                       'goalsHomeTeam': 3,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 701,
                       'referee': None,
                       'round': 'Regular Season - 7',
                       'score': {'extratime': None,
                                 'fulltime': '3-0',
                                 'halftime': '3-0',
                                 'penalty': None},
                       'secondHalfStart': None,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Anfield (Liverpool)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 90,
                       'event_date': '2011-11-27T16:00:00+00:00',
                       'event_timestamp': 1322409600,
                       'firstHalfStart': 1322409600,
                       'fixture_id': 193946,
                       'goalsAwayTeam': 1,
                       'goalsHomeTeam': 1,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 700,
                       'referee': None,
                       'round': 'Regular Season - 13',
                       'score': {'extratime': None,
                                 'fulltime': '1-1',
                                 'halftime': '1-1',
                                 'penalty': None},
                       'secondHalfStart': 1322413200,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Anfield (Liverpool)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2012-01-03T20:00:00+00:00',
                       'event_timestamp': 1325620800,
                       'firstHalfStart': 1325620800,
                       'fixture_id': 194014,
                       'goalsAwayTeam': 0,
                       'goalsHomeTeam': 3,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 700,
                       'referee': None,
                       'round': 'Regular Season - 20',
                       'score': {'extratime': None,
                                 'fulltime': '3-0',
                                 'halftime': '2-0',
                                 'penalty': None},
                       'secondHalfStart': 1325624400,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Etihad Stadium (Manchester)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2012-01-11T19:45:00+00:00',
                       'event_timestamp': 1326311100,
                       'firstHalfStart': 1326311100,
                       'fixture_id': 455601,
                       'goalsAwayTeam': 1,
                       'goalsHomeTeam': 0,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/48.png',
                                  'name': 'League Cup'},
                       'league_id': 2091,
                       'referee': None,
                       'round': 'Semi-finals',
                       'score': {'extratime': None,
                                 'fulltime': '0-1',
                                 'halftime': '0-1',
                                 'penalty': None},
                       'secondHalfStart': 1326314700,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Etihad Stadium (Manchester)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 90,
                       'event_date': '2012-01-25T19:45:00+00:00',
                       'event_timestamp': 1327520700,
                       'firstHalfStart': 1327520700,
                       'fixture_id': 455602,
                       'goalsAwayTeam': 2,
                       'goalsHomeTeam': 2,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/48.png',
                                  'name': 'League Cup'},
                       'league_id': 2091,
                       'referee': None,
                       'round': 'Semi-finals',
                       'score': {'extratime': None,
                                 'fulltime': '2-2',
                                 'halftime': '1-1',
                                 'penalty': None},
                       'secondHalfStart': 1327524300,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Anfield (Liverpool)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 90,
                       'event_date': '2012-08-26T16:00:00+01:00',
                       'event_timestamp': 1345993200,
                       'firstHalfStart': 1345993200,
                       'fixture_id': 193455,
                       'goalsAwayTeam': 2,
                       'goalsHomeTeam': 2,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 699,
                       'referee': None,
                       'round': 'Regular Season - 2',
                       'score': {'extratime': None,
                                 'fulltime': '2-2',
                                 'halftime': '1-0',
                                 'penalty': None},
                       'secondHalfStart': 1345996800,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Anfield (Liverpool)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2013-02-03T16:00:00+00:00',
                       'event_timestamp': 1359907200,
                       'firstHalfStart': 1359907200,
                       'fixture_id': 193686,
                       'goalsAwayTeam': 2,
                       'goalsHomeTeam': 2,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 699,
                       'referee': None,
                       'round': 'Regular Season - 25',
                       'score': {'extratime': None,
                                 'fulltime': '2-2',
                                 'halftime': '1-1',
                                 'penalty': None},
                       'secondHalfStart': 1359910800,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Etihad Stadium (Manchester)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2013-12-26T17:30:00+00:00',
                       'event_timestamp': 1388079000,
                       'firstHalfStart': 1388079000,
                       'fixture_id': 193236,
                       'goalsAwayTeam': 1,
                       'goalsHomeTeam': 2,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 698,
                       'referee': None,
                       'round': 'Regular Season - 18',
                       'score': {'extratime': None,
                                 'fulltime': '2-1',
                                 'halftime': '2-1',
                                 'penalty': None},
                       'secondHalfStart': 1388082600,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Etihad Stadium (Manchester)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 90,
                       'event_date': '2014-04-13T13:37:00+01:00',
                       'event_timestamp': 1397392620,
                       'firstHalfStart': 1397392620,
                       'fixture_id': 193393,
                       'goalsAwayTeam': 2,
                       'goalsHomeTeam': 3,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 698,
                       'referee': None,
                       'round': 'Regular Season - 34',
                       'score': {'extratime': None,
                                 'fulltime': '3-2',
                                 'halftime': '2-0',
                                 'penalty': None},
                       'secondHalfStart': 1397396220,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Anfield (Liverpool)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2014-08-25T20:00:00+01:00',
                       'event_timestamp': 1408993200,
                       'firstHalfStart': 1408993200,
                       'fixture_id': 192696,
                       'goalsAwayTeam': 1,
                       'goalsHomeTeam': 3,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 697,
                       'referee': None,
                       'round': 'Regular Season - 2',
                       'score': {'extratime': None,
                                 'fulltime': '3-1',
                                 'halftime': '1-0',
                                 'penalty': None},
                       'secondHalfStart': 1408996800,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Etihad Stadium (Manchester)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 90,
                       'event_date': '2015-03-01T12:00:00+00:00',
                       'event_timestamp': 1425211200,
                       'firstHalfStart': 1425211200,
                       'fixture_id': 192943,
                       'goalsAwayTeam': 1,
                       'goalsHomeTeam': 2,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 697,
                       'referee': 'Mark Clattenburg, England',
                       'round': 'Regular Season - 27',
                       'score': {'extratime': None,
                                 'fulltime': '2-1',
                                 'halftime': '1-1',
                                 'penalty': None},
                       'secondHalfStart': 1425214800,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Anfield'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2015-11-21T17:30:00+00:00',
                       'event_timestamp': 1448127000,
                       'firstHalfStart': 1448127000,
                       'fixture_id': 192424,
                       'goalsAwayTeam': 4,
                       'goalsHomeTeam': 1,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 696,
                       'referee': 'Jonathan Moss, England',
                       'round': 'Regular Season - 13',
                       'score': {'extratime': None,
                                 'fulltime': '1-4',
                                 'halftime': '1-3',
                                 'penalty': None},
                       'secondHalfStart': 1448130600,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Etihad Stadium'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 120,
                       'event_date': '2016-02-28T16:30:00+00:00',
                       'event_timestamp': 1456677000,
                       'firstHalfStart': 1456677000,
                       'fixture_id': 455226,
                       'goalsAwayTeam': 1,
                       'goalsHomeTeam': 1,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/48.png',
                                  'name': 'League Cup'},
                       'league_id': 2087,
                       'referee': 'Michael Oliver, England',
                       'round': 'Final',
                       'score': {'extratime': '1-1',
                                 'fulltime': '1-1',
                                 'halftime': '0-0',
                                 'penalty': '1-3'},
                       'secondHalfStart': 1456680600,
                       'status': 'Match Finished',
                       'statusShort': 'PEN',
                       'venue': 'Wembley Stadium'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 90,
                       'event_date': '2016-03-02T20:00:00+00:00',
                       'event_timestamp': 1456948800,
                       'firstHalfStart': 1456948800,
                       'fixture_id': 192575,
                       'goalsAwayTeam': 0,
                       'goalsHomeTeam': 3,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 696,
                       'referee': 'Martin Atkinson, England',
                       'round': 'Regular Season - 28',
                       'score': {'extratime': None,
                                 'fulltime': '3-0',
                                 'halftime': '2-0',
                                 'penalty': None},
                       'secondHalfStart': 1456952400,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Anfield'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 90,
                       'event_date': '2016-12-31T17:30:00+00:00',
                       'event_timestamp': 1483205400,
                       'firstHalfStart': 1483205400,
                       'fixture_id': 17509,
                       'goalsAwayTeam': 0,
                       'goalsHomeTeam': 1,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 56,
                       'referee': 'Craig Pawson, England',
                       'round': 'Regular Season - 19',
                       'score': {'extratime': None,
                                 'fulltime': '1-0',
                                 'halftime': '1-0',
                                 'penalty': None},
                       'secondHalfStart': 1483209000,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Anfield'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2017-03-19T16:30:00+00:00',
                       'event_timestamp': 1489941000,
                       'firstHalfStart': 1489941000,
                       'fixture_id': 17414,
                       'goalsAwayTeam': 1,
                       'goalsHomeTeam': 1,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 56,
                       'referee': 'Michael Oliver, England',
                       'round': 'Regular Season - 29',
                       'score': {'extratime': None,
                                 'fulltime': '1-1',
                                 'halftime': '0-0',
                                 'penalty': None},
                       'secondHalfStart': 1489944600,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Etihad Stadium'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2017-09-09T12:30:00+01:00',
                       'event_timestamp': 1504956600,
                       'firstHalfStart': 1504956600,
                       'fixture_id': 11881,
                       'goalsAwayTeam': 0,
                       'goalsHomeTeam': 5,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 37,
                       'referee': 'Jonathan Moss, England',
                       'round': 'Regular Season - 4',
                       'score': {'extratime': None,
                                 'fulltime': '5-0',
                                 'halftime': '2-0',
                                 'penalty': None},
                       'secondHalfStart': 1504960200,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Etihad Stadium'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 90,
                       'event_date': '2018-01-14T16:00:00+00:00',
                       'event_timestamp': 1515945600,
                       'firstHalfStart': 1515945600,
                       'fixture_id': 11683,
                       'goalsAwayTeam': 3,
                       'goalsHomeTeam': 4,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 37,
                       'referee': 'Andre Marriner, England',
                       'round': 'Regular Season - 23',
                       'score': {'extratime': None,
                                 'fulltime': '4-3',
                                 'halftime': '1-1',
                                 'penalty': None},
                       'secondHalfStart': 1515949200,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Anfield'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 90,
                       'event_date': '2018-04-04T19:45:00+01:00',
                       'event_timestamp': 1522867500,
                       'firstHalfStart': 1522867500,
                       'fixture_id': 152631,
                       'goalsAwayTeam': 0,
                       'goalsHomeTeam': 3,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'World',
                                  'flag': None,
                                  'logo': 'https://media.api-sports.io/football/leagues/2.png',
                                  'name': 'UEFA Champions League'},
                       'league_id': 31,
                       'referee': None,
                       'round': 'Quarter-finals',
                       'score': {'extratime': None,
                                 'fulltime': '3-0',
                                 'halftime': '3-0',
                                 'penalty': None},
                       'secondHalfStart': 1522871100,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Anfield (Liverpool)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2018-04-10T19:45:00+01:00',
                       'event_timestamp': 1523385900,
                       'firstHalfStart': 1523385900,
                       'fixture_id': 152632,
                       'goalsAwayTeam': 2,
                       'goalsHomeTeam': 1,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'World',
                                  'flag': None,
                                  'logo': 'https://media.api-sports.io/football/leagues/2.png',
                                  'name': 'UEFA Champions League'},
                       'league_id': 31,
                       'referee': None,
                       'round': 'Quarter-finals',
                       'score': {'extratime': None,
                                 'fulltime': '1-2',
                                 'halftime': '1-0',
                                 'penalty': None},
                       'secondHalfStart': 1523389500,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Etihad Stadium (Manchester)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2018-07-26T01:05:00+01:00',
                       'event_timestamp': 1532563500,
                       'firstHalfStart': 1532563500,
                       'fixture_id': 255641,
                       'goalsAwayTeam': 2,
                       'goalsHomeTeam': 1,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'World',
                                  'flag': None,
                                  'logo': 'https://media.api-sports.io/football/leagues/26.png',
                                  'name': 'International Champions Cup'},
                       'league_id': 1052,
                       'referee': None,
                       'round': 'Regular Season - 1',
                       'score': {'extratime': None,
                                 'fulltime': '1-2',
                                 'halftime': '0-0',
                                 'penalty': None},
                       'secondHalfStart': 1532567100,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'MetLife Stadium (East Rutherford, New '
                                'Jersey)'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 90,
                       'event_date': '2018-10-07T16:30:00+01:00',
                       'event_timestamp': 1538926200,
                       'firstHalfStart': 1538926200,
                       'fixture_id': 140,
                       'goalsAwayTeam': 0,
                       'goalsHomeTeam': 0,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 2,
                       'referee': 'Martin Atkinson, England',
                       'round': 'Regular Season - 8',
                       'score': {'extratime': None,
                                 'fulltime': '0-0',
                                 'halftime': '0-0',
                                 'penalty': None},
                       'secondHalfStart': 1538929800,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Anfield'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2019-01-03T20:00:00+00:00',
                       'event_timestamp': 1546545600,
                       'firstHalfStart': 1546545600,
                       'fixture_id': 271,
                       'goalsAwayTeam': 1,
                       'goalsHomeTeam': 2,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 2,
                       'referee': 'Anthony Taylor, England',
                       'round': 'Regular Season - 21',
                       'score': {'extratime': None,
                                 'fulltime': '2-1',
                                 'halftime': '1-0',
                                 'penalty': None},
                       'secondHalfStart': 1546549200,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Etihad Stadium'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 120,
                       'event_date': '2019-08-04T15:00:00+01:00',
                       'event_timestamp': 1564927200,
                       'firstHalfStart': 1564927200,
                       'fixture_id': 369310,
                       'goalsAwayTeam': 1,
                       'goalsHomeTeam': 1,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/528.png',
                                  'name': 'Community Shield'},
                       'league_id': 1560,
                       'referee': 'Martin Atkinson, England',
                       'round': 'Final',
                       'score': {'extratime': None,
                                 'fulltime': '1-1',
                                 'halftime': '0-1',
                                 'penalty': '4-5'},
                       'secondHalfStart': 1564930800,
                       'status': 'Match Finished',
                       'statusShort': 'PEN',
                       'venue': 'Wembley Stadium'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 90,
                       'event_date': '2019-11-10T16:30:00+00:00',
                       'event_timestamp': 1573403400,
                       'firstHalfStart': 1573403400,
                       'fixture_id': 157128,
                       'goalsAwayTeam': 1,
                       'goalsHomeTeam': 3,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 524,
                       'referee': 'Michael Oliver, England',
                       'round': 'Regular Season - 12',
                       'score': {'extratime': None,
                                 'fulltime': '3-1',
                                 'halftime': '2-0',
                                 'penalty': None},
                       'secondHalfStart': 1573407000,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Anfield'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2020-07-02T20:15:00+01:00',
                       'event_timestamp': 1593717300,
                       'firstHalfStart': 1593717300,
                       'fixture_id': 157331,
                       'goalsAwayTeam': 0,
                       'goalsHomeTeam': 4,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 524,
                       'referee': 'Anthony Taylor, England',
                       'round': 'Regular Season - 32',
                       'score': {'extratime': None,
                                 'fulltime': '4-0',
                                 'halftime': '3-0',
                                 'penalty': None},
                       'secondHalfStart': 1593720900,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Etihad Stadium'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'elapsed': 90,
                       'event_date': '2020-11-08T16:30:00+00:00',
                       'event_timestamp': 1604853000,
                       'firstHalfStart': 1604853000,
                       'fixture_id': 592217,
                       'goalsAwayTeam': 1,
                       'goalsHomeTeam': 1,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 2790,
                       'referee': 'C. Pawson',
                       'round': 'Regular Season - 8',
                       'score': {'extratime': None,
                                 'fulltime': '1-1',
                                 'halftime': '1-1',
                                 'penalty': None},
                       'secondHalfStart': 1604856600,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'Etihad Stadium'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 0,
                       'event_date': '2021-02-06T15:00:00+00:00',
                       'event_timestamp': 1612623600,
                       'firstHalfStart': None,
                       'fixture_id': 592365,
                       'goalsAwayTeam': None,
                       'goalsHomeTeam': None,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/40.png',
                                    'team_id': 40,
                                    'team_name': 'Liverpool'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 2790,
                       'referee': None,
                       'round': 'Regular Season - 23',
                       'score': {'extratime': None,
                                 'fulltime': None,
                                 'halftime': None,
                                 'penalty': None},
                       'secondHalfStart': None,
                       'status': 'Not Started',
                       'statusShort': 'NS',
                       'venue': 'Anfield'}],
         'results': 29,
         'teams': [{'statistics': {'draws': {'away': 3, 'home': 6, 'total': 9},
                                   'loses': {'away': 7, 'home': 0, 'total': 7},
                                   'played': {'away': 14,
                                              'home': 14,
                                              'total': 28},
                                   'wins': {'away': 4, 'home': 8, 'total': 12}},
                    'team_id': 40,
                    'team_logo': 'https://media.api-sports.io/football/teams/40.png',
                    'team_name': 'Liverpool'},
                   {'statistics': {'draws': {'away': 6, 'home': 3, 'total': 9},
                                   'loses': {'away': 8, 'home': 4, 'total': 12},
                                   'played': {'away': 14,
                                              'home': 14,
                                              'total': 28},
                                   'wins': {'away': 0, 'home': 7, 'total': 7}},
                    'team_id': 50,
                    'team_logo': 'https://media.api-sports.io/football/teams/50.png',
                    'team_name': 'Manchester City'}]}}