onegame = {'api':{'fixture':[{'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/50.png',
                                    'team_id': 50,
                                    'team_name': 'Manchester City'},
                       'elapsed': 90,
                       'event_date': '2019-05-12T15:00:00+01:00',
                       'event_timestamp': 1557669600,
                       'firstHalfStart': 1557669600,
                       'fixture_id': 435,
                       'goalsAwayTeam': 4,
                       'goalsHomeTeam': 1,
                       'homeTeam': {'logo': 'https://media.api-sports.io/football/teams/51.png',
                                    'team_id': 51,
                                    'team_name': 'Brighton'},
                       'league': {'country': 'England',
                                  'flag': 'https://media.api-sports.io/flags/gb.svg',
                                  'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                  'name': 'Premier League'},
                       'league_id': 2,
                       'referee': 'Michael Oliver, England',
                       'round': 'Regular Season - 38',
                       'score': {'extratime': None,
                                 'fulltime': '1-4',
                                 'halftime': '1-2',
                                 'penalty': None},
                       'secondHalfStart': 1557673200,
                       'status': 'Match Finished',
                       'statusShort': 'FT',
                       'venue': 'American Express Community Stadium'},
                      {'awayTeam': {'logo': 'https://media.api-sports.io/football/teams/42.png',
                                    'team_id': 42,
                                    'team_name': 'Arsenal'},
                       'elapsed': 90,
                       'event_date': '2019-05-12T15:00:00+01:00',
                       'event_timestamp': 1557669600,
                       'firstHalfStart': 1557669600}],

        'result': 1}}