
table = {'api': {'errors': [],
                'get': 'standings',
                'paging': {'current': 1, 'total': 1},
                'parameters': {'league': '39', 'season': '2020'},
                'response': [{'league': {'country': 'England',
                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                        'id': 39,
                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                        'name': 'Premier League',
                                        'season': 2020,
                                        'standings': [[{'all': {'draw': 0,
                                                                'goals': {'against': 9,
                                                                        'for': 18},
                                                                'lose': 2,
                                                                'played': 8,
                                                                'win': 6},
                                                        'away': {'draw': 0,
                                                                'goals': {'against': 3,
                                                                        'for': 13},
                                                                'lose': 0,
                                                                'played': 4,
                                                                'win': 4},
                                                        'description': 'Promotion - '
                                                                        'Champions League '
                                                                        '(Group Stage)',
                                                        'form': 'WWWLL',
                                                        'goalsDiff': 9,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 0,
                                                                'goals': {'against': 6,
                                                                        'for': 5},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 2},
                                                        'points': 18,
                                                        'rank': 1,
                                                        'status': 'same',
                                                        'team': {'id': 46,
                                                                'logo': 'https://media.api-sports.io/football/teams/46.png',
                                                                'name': 'Leicester'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 2,
                                                                'goals': {'against': 9,
                                                                        'for': 19},
                                                                'lose': 1,
                                                                'played': 8,
                                                                'win': 5},
                                                        'away': {'draw': 0,
                                                                'goals': {'against': 3,
                                                                        'for': 13},
                                                                'lose': 0,
                                                                'played': 4,
                                                                'win': 4},
                                                        'description': 'Promotion - '
                                                                        'Champions League '
                                                                        '(Group Stage)',
                                                        'form': 'WWWDW',
                                                        'goalsDiff': 10,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 2,
                                                                'goals': {'against': 6,
                                                                        'for': 6},
                                                                'lose': 1,
                                                                'played': 4,
                                                                'win': 1},
                                                        'points': 17,
                                                        'rank': 2,
                                                        'status': 'same',
                                                        'team': {'id': 47,
                                                                'logo': 'https://media.api-sports.io/football/teams/47.png',
                                                                'name': 'Tottenham'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 2,
                                                                'goals': {'against': 16,
                                                                        'for': 18},
                                                                'lose': 1,
                                                                'played': 8,
                                                                'win': 5},
                                                        'away': {'draw': 2,
                                                                'goals': {'against': 10,
                                                                        'for': 7},
                                                                'lose': 1,
                                                                'played': 4,
                                                                'win': 1},
                                                        'description': 'Promotion - '
                                                                        'Champions League '
                                                                        '(Group Stage)',
                                                        'form': 'DWWDL',
                                                        'goalsDiff': 2,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 0,
                                                                'goals': {'against': 6,
                                                                        'for': 11},
                                                                'lose': 0,
                                                                'played': 4,
                                                                'win': 4},
                                                        'points': 17,
                                                        'rank': 3,
                                                        'status': 'same',
                                                        'team': {'id': 40,
                                                                'logo': 'https://media.api-sports.io/football/teams/40.png',
                                                                'name': 'Liverpool'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 1,
                                                                'goals': {'against': 12,
                                                                        'for': 16},
                                                                'lose': 2,
                                                                'played': 8,
                                                                'win': 5},
                                                        'away': {'draw': 1,
                                                                'goals': {'against': 7,
                                                                        'for': 8},
                                                                'lose': 1,
                                                                'played': 4,
                                                                'win': 2},
                                                        'description': 'Promotion - '
                                                                        'Champions League '
                                                                        '(Group Stage)',
                                                        'form': 'WWWDW',
                                                        'goalsDiff': 4,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 0,
                                                                'goals': {'against': 5,
                                                                        'for': 8},
                                                                'lose': 1,
                                                                'played': 4,
                                                                'win': 3},
                                                        'points': 16,
                                                        'rank': 4,
                                                        'status': 'same',
                                                        'team': {'id': 41,
                                                                'logo': 'https://media.api-sports.io/football/teams/41.png',
                                                                'name': 'Southampton'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 3,
                                                                'goals': {'against': 10,
                                                                        'for': 20},
                                                                'lose': 1,
                                                                'played': 8,
                                                                'win': 4},
                                                        'away': {'draw': 2,
                                                                'goals': {'against': 4,
                                                                        'for': 9},
                                                                'lose': 0,
                                                                'played': 4,
                                                                'win': 2},
                                                        'description': 'Promotion - Europa '
                                                                        'League (Group Stage)',
                                                        'form': 'WWDDW',
                                                        'goalsDiff': 10,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 1,
                                                                'goals': {'against': 6,
                                                                        'for': 11},
                                                                'lose': 1,
                                                                'played': 4,
                                                                'win': 2},
                                                        'points': 15,
                                                        'rank': 5,
                                                        'status': 'same',
                                                        'team': {'id': 49,
                                                                'logo': 'https://media.api-sports.io/football/teams/49.png',
                                                                'name': 'Chelsea'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 0,
                                                                'goals': {'against': 9,
                                                                        'for': 18},
                                                                'lose': 2,
                                                                'played': 7,
                                                                'win': 5},
                                                        'away': {'draw': 0,
                                                                'goals': {'against': 0,
                                                                        'for': 7},
                                                                'lose': 0,
                                                                'played': 3,
                                                                'win': 3},
                                                        'description': None,
                                                        'form': 'WLLWW',
                                                        'goalsDiff': 9,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 0,
                                                                'goals': {'against': 9,
                                                                        'for': 11},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 2},
                                                        'points': 15,
                                                        'rank': 6,
                                                        'status': 'same',
                                                        'team': {'id': 66,
                                                                'logo': 'https://media.api-sports.io/football/teams/66.png',
                                                                'name': 'Aston Villa'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 1,
                                                                'goals': {'against': 14,
                                                                        'for': 16},
                                                                'lose': 3,
                                                                'played': 8,
                                                                'win': 4},
                                                        'away': {'draw': 0,
                                                                'goals': {'against': 5,
                                                                        'for': 4},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 2},
                                                        'description': None,
                                                        'form': 'LLLDW',
                                                        'goalsDiff': 2,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 1,
                                                                'goals': {'against': 9,
                                                                        'for': 12},
                                                                'lose': 1,
                                                                'played': 4,
                                                                'win': 2},
                                                        'points': 13,
                                                        'rank': 7,
                                                        'status': 'same',
                                                        'team': {'id': 45,
                                                                'logo': 'https://media.api-sports.io/football/teams/45.png',
                                                                'name': 'Everton'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 1,
                                                                'goals': {'against': 12,
                                                                        'for': 12},
                                                                'lose': 3,
                                                                'played': 8,
                                                                'win': 4},
                                                        'away': {'draw': 0,
                                                                'goals': {'against': 8,
                                                                        'for': 5},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 2},
                                                        'description': None,
                                                        'form': 'WLWDL',
                                                        'goalsDiff': 0,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 1,
                                                                'goals': {'against': 4,
                                                                        'for': 7},
                                                                'lose': 1,
                                                                'played': 4,
                                                                'win': 2},
                                                        'points': 13,
                                                        'rank': 8,
                                                        'status': 'same',
                                                        'team': {'id': 52,
                                                                'logo': 'https://media.api-sports.io/football/teams/52.png',
                                                                'name': 'Crystal Palace'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 1,
                                                                'goals': {'against': 9,
                                                                        'for': 8},
                                                                'lose': 3,
                                                                'played': 8,
                                                                'win': 4},
                                                        'away': {'draw': 0,
                                                                'goals': {'against': 5,
                                                                        'for': 3},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 2},
                                                        'description': None,
                                                        'form': 'LWDWW',
                                                        'goalsDiff': -1,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 1,
                                                                'goals': {'against': 4,
                                                                        'for': 5},
                                                                'lose': 1,
                                                                'played': 4,
                                                                'win': 2},
                                                        'points': 13,
                                                        'rank': 9,
                                                        'status': 'same',
                                                        'team': {'id': 39,
                                                                'logo': 'https://media.api-sports.io/football/teams/39.png',
                                                                'name': 'Wolves'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 3,
                                                                'goals': {'against': 9,
                                                                        'for': 10},
                                                                'lose': 1,
                                                                'played': 7,
                                                                'win': 3},
                                                        'away': {'draw': 2,
                                                                'goals': {'against': 3,
                                                                        'for': 6},
                                                                'lose': 0,
                                                                'played': 4,
                                                                'win': 2},
                                                        'description': None,
                                                        'form': 'DWDWD',
                                                        'goalsDiff': 1,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 1,
                                                                'goals': {'against': 6,
                                                                        'for': 4},
                                                                'lose': 1,
                                                                'played': 3,
                                                                'win': 1},
                                                        'points': 12,
                                                        'rank': 10,
                                                        'status': 'same',
                                                        'team': {'id': 50,
                                                                'logo': 'https://media.api-sports.io/football/teams/50.png',
                                                                'name': 'Manchester City'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 0,
                                                                'goals': {'against': 10,
                                                                        'for': 9},
                                                                'lose': 4,
                                                                'played': 8,
                                                                'win': 4},
                                                        'away': {'draw': 0,
                                                                'goals': {'against': 4,
                                                                        'for': 5},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 2},
                                                        'description': None,
                                                        'form': 'LWLLW',
                                                        'goalsDiff': -1,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 0,
                                                                'goals': {'against': 6,
                                                                        'for': 4},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 2},
                                                        'points': 12,
                                                        'rank': 11,
                                                        'status': 'same',
                                                        'team': {'id': 42,
                                                                'logo': 'https://media.api-sports.io/football/teams/42.png',
                                                                'name': 'Arsenal'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 2,
                                                                'goals': {'against': 10,
                                                                        'for': 14},
                                                                'lose': 3,
                                                                'played': 8,
                                                                'win': 3},
                                                        'away': {'draw': 1,
                                                                'goals': {'against': 7,
                                                                        'for': 8},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 1},
                                                        'description': None,
                                                        'form': 'WLDDW',
                                                        'goalsDiff': 4,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 1,
                                                                'goals': {'against': 3,
                                                                        'for': 6},
                                                                'lose': 1,
                                                                'played': 4,
                                                                'win': 2},
                                                        'points': 11,
                                                        'rank': 12,
                                                        'status': 'same',
                                                        'team': {'id': 48,
                                                                'logo': 'https://media.api-sports.io/football/teams/48.png',
                                                                'name': 'West Ham'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 2,
                                                                'goals': {'against': 13,
                                                                        'for': 10},
                                                                'lose': 3,
                                                                'played': 8,
                                                                'win': 3},
                                                        'away': {'draw': 2,
                                                                'goals': {'against': 4,
                                                                        'for': 4},
                                                                'lose': 1,
                                                                'played': 4,
                                                                'win': 1},
                                                        'description': None,
                                                        'form': 'LWDLW',
                                                        'goalsDiff': -3,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 0,
                                                                'goals': {'against': 9,
                                                                        'for': 6},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 2},
                                                        'points': 11,
                                                        'rank': 13,
                                                        'status': 'same',
                                                        'team': {'id': 34,
                                                                'logo': 'https://media.api-sports.io/football/teams/34.png',
                                                                'name': 'Newcastle'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 1,
                                                                'goals': {'against': 14,
                                                                        'for': 12},
                                                                'lose': 3,
                                                                'played': 7,
                                                                'win': 3},
                                                        'away': {'draw': 0,
                                                                'goals': {'against': 4,
                                                                        'for': 10},
                                                                'lose': 0,
                                                                'played': 3,
                                                                'win': 3},
                                                        'description': None,
                                                        'form': 'WLDWL',
                                                        'goalsDiff': -2,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 1,
                                                                'goals': {'against': 10,
                                                                        'for': 2},
                                                                'lose': 3,
                                                                'played': 4,
                                                                'win': 0},
                                                        'points': 10,
                                                        'rank': 14,
                                                        'status': 'same',
                                                        'team': {'id': 33,
                                                                'logo': 'https://media.api-sports.io/football/teams/33.png',
                                                                'name': 'Manchester United'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 1,
                                                                'goals': {'against': 17,
                                                                        'for': 14},
                                                                'lose': 4,
                                                                'played': 8,
                                                                'win': 3},
                                                        'away': {'draw': 0,
                                                                'goals': {'against': 8,
                                                                        'for': 8},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 2},
                                                        'description': None,
                                                        'form': 'LLWLD',
                                                        'goalsDiff': -3,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 1,
                                                                'goals': {'against': 9,
                                                                        'for': 6},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 1},
                                                        'points': 10,
                                                        'rank': 15,
                                                        'status': 'same',
                                                        'team': {'id': 63,
                                                                'logo': 'https://media.api-sports.io/football/teams/63.png',
                                                                'name': 'Leeds'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 3,
                                                                'goals': {'against': 14,
                                                                        'for': 11},
                                                                'lose': 4,
                                                                'played': 8,
                                                                'win': 1},
                                                        'away': {'draw': 1,
                                                                'goals': {'against': 7,
                                                                        'for': 7},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 1},
                                                        'description': None,
                                                        'form': 'DLDDL',
                                                        'goalsDiff': -3,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 2,
                                                                'goals': {'against': 7,
                                                                        'for': 4},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 0},
                                                        'points': 6,
                                                        'rank': 16,
                                                        'status': 'same',
                                                        'team': {'id': 51,
                                                                'logo': 'https://media.api-sports.io/football/teams/51.png',
                                                                'name': 'Brighton'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 1,
                                                                'goals': {'against': 15,
                                                                        'for': 7},
                                                                'lose': 6,
                                                                'played': 8,
                                                                'win': 1},
                                                        'away': {'draw': 1,
                                                                'goals': {'against': 7,
                                                                        'for': 4},
                                                                'lose': 3,
                                                                'played': 4,
                                                                'win': 0},
                                                        'description': None,
                                                        'form': 'LWLDL',
                                                        'goalsDiff': -8,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 0,
                                                                'goals': {'against': 8,
                                                                        'for': 3},
                                                                'lose': 3,
                                                                'played': 4,
                                                                'win': 1},
                                                        'points': 4,
                                                        'rank': 17,
                                                        'status': 'same',
                                                        'team': {'id': 36,
                                                                'logo': 'https://media.api-sports.io/football/teams/36.png',
                                                                'name': 'Fulham'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 3,
                                                                'goals': {'against': 17,
                                                                        'for': 6},
                                                                'lose': 5,
                                                                'played': 8,
                                                                'win': 0},
                                                        'away': {'draw': 1,
                                                                'goals': {'against': 10,
                                                                        'for': 3},
                                                                'lose': 3,
                                                                'played': 4,
                                                                'win': 0},
                                                        'description': 'Relegation - '
                                                                        'Championship',
                                                        'form': 'LLDDL',
                                                        'goalsDiff': -11,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 2,
                                                                'goals': {'against': 7,
                                                                        'for': 3},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 0},
                                                        'points': 3,
                                                        'rank': 18,
                                                        'status': 'same',
                                                        'team': {'id': 60,
                                                                'logo': 'https://media.api-sports.io/football/teams/60.png',
                                                                'name': 'West Brom'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 2,
                                                                'goals': {'against': 12,
                                                                        'for': 3},
                                                                'lose': 5,
                                                                'played': 7,
                                                                'win': 0},
                                                        'away': {'draw': 2,
                                                                'goals': {'against': 7,
                                                                        'for': 3},
                                                                'lose': 2,
                                                                'played': 4,
                                                                'win': 0},
                                                        'description': 'Relegation - '
                                                                        'Championship',
                                                        'form': 'DLLDL',
                                                        'goalsDiff': -9,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 0,
                                                                'goals': {'against': 5,
                                                                        'for': 0},
                                                                'lose': 3,
                                                                'played': 3,
                                                                'win': 0},
                                                        'points': 2,
                                                        'rank': 19,
                                                        'status': 'same',
                                                        'team': {'id': 44,
                                                                'logo': 'https://media.api-sports.io/football/teams/44.png',
                                                                'name': 'Burnley'},
                                                        'update': '2020-11-08T00:00:00+00:00'},
                                                        {'all': {'draw': 1,
                                                                'goals': {'against': 14,
                                                                        'for': 4},
                                                                'lose': 7,
                                                                'played': 8,
                                                                'win': 0},
                                                        'away': {'draw': 0,
                                                                'goals': {'against': 9,
                                                                        'for': 3},
                                                                'lose': 4,
                                                                'played': 4,
                                                                'win': 0},
                                                        'description': 'Relegation - '
                                                                        'Championship',
                                                        'form': 'LLLDL',
                                                        'goalsDiff': -10,
                                                        'group': 'Premier League',
                                                        'home': {'draw': 1,
                                                                'goals': {'against': 5,
                                                                        'for': 1},
                                                                'lose': 3,
                                                                'played': 4,
                                                                'win': 0},
                                                        'points': 1,
                                                        'rank': 20,
                                                        'status': 'same',
                                                        'team': {'id': 62,
                                                                'logo': 'https://media.api-sports.io/football/teams/62.png',
                                                                'name': 'Sheffield Utd'},
                                                        'update': '2020-11-08T00:00:00+00:00'}]]}}],
                'results': 1}}