table = {'errors': [],
        'get': 'standings',
        'paging': {'current': 1, 'total': 1},
        'parameters': {'league': '39', 'season': '2020'},
        'response': [{'league': {'country': 'England',
                                'flag': 'https://media.api-sports.io/flags/gb.svg',
                                'id': 39,
                                'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                'name': 'Premier League',
                                'season': 2020,
                                'standings': [[{'all': {'draw': 4,
                                                        'goals': {'against': 19,
                                                                'for': 29},
                                                        'lose': 1,
                                                        'played': 13,
                                                        'win': 8},
                                                'away': {'draw': 4,
                                                        'goals': {'against': 12,
                                                                'for': 9},
                                                        'lose': 1,
                                                        'played': 6,
                                                        'win': 1},
                                                'description': 'Promotion - '
                                                                'Champions League '
                                                                '(Group Stage)',
                                                'form': 'WDWDW',
                                                'goalsDiff': 10,
                                                'group': 'Premier League',
                                                'home': {'draw': 0,
                                                        'goals': {'against': 7,
                                                                'for': 20},
                                                        'lose': 0,
                                                        'played': 7,
                                                        'win': 7},
                                                'points': 28,
                                                'rank': 1,
                                                'status': 'same',
                                                'team': {'id': 40,
                                                        'logo': 'https://media.api-sports.io/football/teams/40.png',
                                                        'name': 'Liverpool'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 4,
                                                        'goals': {'against': 12,
                                                                'for': 25},
                                                        'lose': 2,
                                                        'played': 13,
                                                        'win': 7},
                                                'away': {'draw': 2,
                                                        'goals': {'against': 6,
                                                                'for': 15},
                                                        'lose': 1,
                                                        'played': 7,
                                                        'win': 4},
                                                'description': 'Promotion - '
                                                                'Champions League '
                                                                '(Group Stage)',
                                                'form': 'LDWDW',
                                                'goalsDiff': 13,
                                                'group': 'Premier League',
                                                'home': {'draw': 2,
                                                        'goals': {'against': 6,
                                                                'for': 10},
                                                        'lose': 1,
                                                        'played': 6,
                                                        'win': 3},
                                                'points': 25,
                                                'rank': 2,
                                                'status': 'same',
                                                'team': {'id': 47,
                                                        'logo': 'https://media.api-sports.io/football/teams/47.png',
                                                        'name': 'Tottenham'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 3,
                                                        'goals': {'against': 18,
                                                                'for': 25},
                                                        'lose': 3,
                                                        'played': 13,
                                                        'win': 7},
                                                'away': {'draw': 3,
                                                        'goals': {'against': 10,
                                                                'for': 12},
                                                        'lose': 1,
                                                        'played': 7,
                                                        'win': 3},
                                                'description': 'Promotion - '
                                                                'Champions League '
                                                                '(Group Stage)',
                                                'form': 'DWWLD',
                                                'goalsDiff': 7,
                                                'group': 'Premier League',
                                                'home': {'draw': 0,
                                                        'goals': {'against': 8,
                                                                'for': 13},
                                                        'lose': 2,
                                                        'played': 6,
                                                        'win': 4},
                                                'points': 24,
                                                'rank': 3,
                                                'status': 'same',
                                                'team': {'id': 41,
                                                        'logo': 'https://media.api-sports.io/football/teams/41.png',
                                                        'name': 'Southampton'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 0,
                                                        'goals': {'against': 17,
                                                                'for': 24},
                                                        'lose': 5,
                                                        'played': 13,
                                                        'win': 8},
                                                'away': {'draw': 0,
                                                        'goals': {'against': 7,
                                                                'for': 15},
                                                        'lose': 1,
                                                        'played': 6,
                                                        'win': 5},
                                                'description': 'Promotion - '
                                                                'Champions League '
                                                                '(Group Stage)',
                                                'form': 'LWWLL',
                                                'goalsDiff': 7,
                                                'group': 'Premier League',
                                                'home': {'draw': 0,
                                                        'goals': {'against': 10,
                                                                'for': 9},
                                                        'lose': 4,
                                                        'played': 7,
                                                        'win': 3},
                                                'points': 24,
                                                'rank': 4,
                                                'status': 'same',
                                                'team': {'id': 46,
                                                        'logo': 'https://media.api-sports.io/football/teams/46.png',
                                                        'name': 'Leicester'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 2,
                                                        'goals': {'against': 18,
                                                                'for': 23},
                                                        'lose': 4,
                                                        'played': 13,
                                                        'win': 7},
                                                'away': {'draw': 1,
                                                        'goals': {'against': 8,
                                                                'for': 10},
                                                        'lose': 2,
                                                        'played': 7,
                                                        'win': 4},
                                                'description': 'Promotion - Europa '
                                                                'League (Group Stage)',
                                                'form': 'WWDLW',
                                                'goalsDiff': 5,
                                                'group': 'Premier League',
                                                'home': {'draw': 1,
                                                        'goals': {'against': 10,
                                                                'for': 13},
                                                        'lose': 2,
                                                        'played': 6,
                                                        'win': 3},
                                                'points': 23,
                                                'rank': 5,
                                                'status': 'same',
                                                'team': {'id': 45,
                                                        'logo': 'https://media.api-sports.io/football/teams/45.png',
                                                        'name': 'Everton'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 2,
                                                        'goals': {'against': 19,
                                                                'for': 22},
                                                        'lose': 3,
                                                        'played': 12,
                                                        'win': 7},
                                                'away': {'draw': 0,
                                                        'goals': {'against': 9,
                                                                'for': 19},
                                                        'lose': 0,
                                                        'played': 6,
                                                        'win': 6},
                                                'description': None,
                                                'form': 'WDWWW',
                                                'goalsDiff': 3,
                                                'group': 'Premier League',
                                                'home': {'draw': 2,
                                                        'goals': {'against': 10,
                                                                'for': 3},
                                                        'lose': 3,
                                                        'played': 6,
                                                        'win': 1},
                                                'points': 23,
                                                'rank': 6,
                                                'status': 'same',
                                                'team': {'id': 33,
                                                        'logo': 'https://media.api-sports.io/football/teams/33.png',
                                                        'name': 'Manchester United'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 4,
                                                        'goals': {'against': 14,
                                                                'for': 26},
                                                        'lose': 3,
                                                        'played': 13,
                                                        'win': 6},
                                                'away': {'draw': 2,
                                                        'goals': {'against': 7,
                                                                'for': 12},
                                                        'lose': 2,
                                                        'played': 7,
                                                        'win': 3},
                                                'description': None,
                                                'form': 'LLWDW',
                                                'goalsDiff': 12,
                                                'group': 'Premier League',
                                                'home': {'draw': 2,
                                                        'goals': {'against': 7,
                                                                'for': 14},
                                                        'lose': 1,
                                                        'played': 6,
                                                        'win': 3},
                                                'points': 22,
                                                'rank': 7,
                                                'status': 'same',
                                                'team': {'id': 49,
                                                        'logo': 'https://media.api-sports.io/football/teams/49.png',
                                                        'name': 'Chelsea'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 3,
                                                        'goals': {'against': 16,
                                                                'for': 21},
                                                        'lose': 4,
                                                        'played': 13,
                                                        'win': 6},
                                                'away': {'draw': 1,
                                                        'goals': {'against': 8,
                                                                'for': 11},
                                                        'lose': 2,
                                                        'played': 6,
                                                        'win': 3},
                                                'description': None,
                                                'form': 'DWLWW',
                                                'goalsDiff': 5,
                                                'group': 'Premier League',
                                                'home': {'draw': 2,
                                                        'goals': {'against': 8,
                                                                'for': 10},
                                                        'lose': 2,
                                                        'played': 7,
                                                        'win': 3},
                                                'points': 21,
                                                'rank': 8,
                                                'status': 'same',
                                                'team': {'id': 48,
                                                        'logo': 'https://media.api-sports.io/football/teams/48.png',
                                                        'name': 'West Ham'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 5,
                                                        'goals': {'against': 12,
                                                                'for': 18},
                                                        'lose': 2,
                                                        'played': 12,
                                                        'win': 5},
                                                'away': {'draw': 3,
                                                        'goals': {'against': 5,
                                                                'for': 6},
                                                        'lose': 1,
                                                        'played': 6,
                                                        'win': 2},
                                                'description': None,
                                                'form': 'DDWWL',
                                                'goalsDiff': 6,
                                                'group': 'Premier League',
                                                'home': {'draw': 2,
                                                        'goals': {'against': 7,
                                                                'for': 12},
                                                        'lose': 1,
                                                        'played': 6,
                                                        'win': 3},
                                                'points': 20,
                                                'rank': 9,
                                                'status': 'same',
                                                'team': {'id': 50,
                                                        'logo': 'https://media.api-sports.io/football/teams/50.png',
                                                        'name': 'Manchester City'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 2,
                                                        'goals': {'against': 17,
                                                                'for': 13},
                                                        'lose': 5,
                                                        'played': 13,
                                                        'win': 6},
                                                'away': {'draw': 0,
                                                        'goals': {'against': 10,
                                                                'for': 5},
                                                        'lose': 3,
                                                        'played': 6,
                                                        'win': 3},
                                                'description': None,
                                                'form': 'WLLWD',
                                                'goalsDiff': -4,
                                                'group': 'Premier League',
                                                'home': {'draw': 2,
                                                        'goals': {'against': 7,
                                                                'for': 8},
                                                        'lose': 2,
                                                        'played': 7,
                                                        'win': 3},
                                                'points': 20,
                                                'rank': 10,
                                                'status': 'same',
                                                'team': {'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/teams/39.png',
                                                        'name': 'Wolves'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 1,
                                                        'goals': {'against': 13,
                                                                'for': 21},
                                                        'lose': 4,
                                                        'played': 11,
                                                        'win': 6},
                                                'away': {'draw': 0,
                                                        'goals': {'against': 2,
                                                                'for': 9},
                                                        'lose': 1,
                                                        'played': 5,
                                                        'win': 4},
                                                'description': None,
                                                'form': 'DWLLW',
                                                'goalsDiff': 8,
                                                'group': 'Premier League',
                                                'home': {'draw': 1,
                                                        'goals': {'against': 11,
                                                                'for': 12},
                                                        'lose': 3,
                                                        'played': 6,
                                                        'win': 2},
                                                'points': 19,
                                                'rank': 11,
                                                'status': 'same',
                                                'team': {'id': 66,
                                                        'logo': 'https://media.api-sports.io/football/teams/66.png',
                                                        'name': 'Aston Villa'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 3,
                                                        'goals': {'against': 18,
                                                                'for': 19},
                                                        'lose': 5,
                                                        'played': 13,
                                                        'win': 5},
                                                'away': {'draw': 1,
                                                        'goals': {'against': 11,
                                                                'for': 11},
                                                        'lose': 3,
                                                        'played': 7,
                                                        'win': 3},
                                                'description': None,
                                                'form': 'DDWLL',
                                                'goalsDiff': 1,
                                                'group': 'Premier League',
                                                'home': {'draw': 2,
                                                        'goals': {'against': 7,
                                                                'for': 8},
                                                        'lose': 2,
                                                        'played': 6,
                                                        'win': 2},
                                                'points': 18,
                                                'rank': 12,
                                                'status': 'same',
                                                'team': {'id': 52,
                                                        'logo': 'https://media.api-sports.io/football/teams/52.png',
                                                        'name': 'Crystal Palace'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 2,
                                                        'goals': {'against': 24,
                                                                'for': 22},
                                                        'lose': 6,
                                                        'played': 13,
                                                        'win': 5},
                                                'away': {'draw': 0,
                                                        'goals': {'against': 11,
                                                                'for': 10},
                                                        'lose': 3,
                                                        'played': 6,
                                                        'win': 3},
                                                'description': None,
                                                'form': 'WLLWD',
                                                'goalsDiff': -2,
                                                'group': 'Premier League',
                                                'home': {'draw': 2,
                                                        'goals': {'against': 13,
                                                                'for': 12},
                                                        'lose': 3,
                                                        'played': 7,
                                                        'win': 2},
                                                'points': 17,
                                                'rank': 13,
                                                'status': 'same',
                                                'team': {'id': 63,
                                                        'logo': 'https://media.api-sports.io/football/teams/63.png',
                                                        'name': 'Leeds'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 2,
                                                        'goals': {'against': 21,
                                                                'for': 16},
                                                        'lose': 5,
                                                        'played': 12,
                                                        'win': 5},
                                                'away': {'draw': 2,
                                                        'goals': {'against': 9,
                                                                'for': 8},
                                                        'lose': 2,
                                                        'played': 6,
                                                        'win': 2},
                                                'description': None,
                                                'form': 'LWWLL',
                                                'goalsDiff': -5,
                                                'group': 'Premier League',
                                                'home': {'draw': 0,
                                                        'goals': {'against': 12,
                                                                'for': 8},
                                                        'lose': 3,
                                                        'played': 6,
                                                        'win': 3},
                                                'points': 17,
                                                'rank': 14,
                                                'status': 'same',
                                                'team': {'id': 34,
                                                        'logo': 'https://media.api-sports.io/football/teams/34.png',
                                                        'name': 'Newcastle'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 2,
                                                        'goals': {'against': 16,
                                                                'for': 11},
                                                        'lose': 7,
                                                        'played': 13,
                                                        'win': 4},
                                                'away': {'draw': 1,
                                                        'goals': {'against': 6,
                                                                'for': 5},
                                                        'lose': 3,
                                                        'played': 6,
                                                        'win': 2},
                                                'description': None,
                                                'form': 'DLLLD',
                                                'goalsDiff': -5,
                                                'group': 'Premier League',
                                                'home': {'draw': 1,
                                                        'goals': {'against': 10,
                                                                'for': 6},
                                                        'lose': 4,
                                                        'played': 7,
                                                        'win': 2},
                                                'points': 14,
                                                'rank': 15,
                                                'status': 'same',
                                                'team': {'id': 42,
                                                        'logo': 'https://media.api-sports.io/football/teams/42.png',
                                                        'name': 'Arsenal'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 5,
                                                        'goals': {'against': 21,
                                                                'for': 15},
                                                        'lose': 6,
                                                        'played': 13,
                                                        'win': 2},
                                                'away': {'draw': 2,
                                                        'goals': {'against': 11,
                                                                'for': 9},
                                                        'lose': 3,
                                                        'played': 7,
                                                        'win': 2},
                                                'description': None,
                                                'form': 'DLLDW',
                                                'goalsDiff': -6,
                                                'group': 'Premier League',
                                                'home': {'draw': 3,
                                                        'goals': {'against': 10,
                                                                'for': 6},
                                                        'lose': 3,
                                                        'played': 6,
                                                        'win': 0},
                                                'points': 11,
                                                'rank': 16,
                                                'status': 'same',
                                                'team': {'id': 51,
                                                        'logo': 'https://media.api-sports.io/football/teams/51.png',
                                                        'name': 'Brighton'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 4,
                                                        'goals': {'against': 18,
                                                                'for': 6},
                                                        'lose': 6,
                                                        'played': 12,
                                                        'win': 2},
                                                'away': {'draw': 3,
                                                        'goals': {'against': 12,
                                                                'for': 4},
                                                        'lose': 3,
                                                        'played': 7,
                                                        'win': 1},
                                                'description': None,
                                                'form': 'DWDLW',
                                                'goalsDiff': -12,
                                                'group': 'Premier League',
                                                'home': {'draw': 1,
                                                        'goals': {'against': 6,
                                                                'for': 2},
                                                        'lose': 3,
                                                        'played': 5,
                                                        'win': 1},
                                                'points': 10,
                                                'rank': 17,
                                                'status': 'same',
                                                'team': {'id': 44,
                                                        'logo': 'https://media.api-sports.io/football/teams/44.png',
                                                        'name': 'Burnley'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 3,
                                                        'goals': {'against': 22,
                                                                'for': 12},
                                                        'lose': 8,
                                                        'played': 13,
                                                        'win': 2},
                                                'away': {'draw': 1,
                                                        'goals': {'against': 10,
                                                                'for': 6},
                                                        'lose': 4,
                                                        'played': 6,
                                                        'win': 1},
                                                'description': 'Relegation - '
                                                                'Championship',
                                                'form': 'DDLWL',
                                                'goalsDiff': -10,
                                                'group': 'Premier League',
                                                'home': {'draw': 2,
                                                        'goals': {'against': 12,
                                                                'for': 6},
                                                        'lose': 4,
                                                        'played': 7,
                                                        'win': 1},
                                                'points': 9,
                                                'rank': 18,
                                                'status': 'same',
                                                'team': {'id': 36,
                                                        'logo': 'https://media.api-sports.io/football/teams/36.png',
                                                        'name': 'Fulham'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 4,
                                                        'goals': {'against': 26,
                                                                'for': 10},
                                                        'lose': 8,
                                                        'played': 13,
                                                        'win': 1},
                                                'away': {'draw': 2,
                                                        'goals': {'against': 14,
                                                                'for': 5},
                                                        'lose': 5,
                                                        'played': 7,
                                                        'win': 0},
                                                'description': 'Relegation - '
                                                                'Championship',
                                                'form': 'DLLWL',
                                                'goalsDiff': -16,
                                                'group': 'Premier League',
                                                'home': {'draw': 2,
                                                        'goals': {'against': 12,
                                                                'for': 5},
                                                        'lose': 3,
                                                        'played': 6,
                                                        'win': 1},
                                                'points': 7,
                                                'rank': 19,
                                                'status': 'same',
                                                'team': {'id': 60,
                                                        'logo': 'https://media.api-sports.io/football/teams/60.png',
                                                        'name': 'West Brom'},
                                                'update': '2020-12-17T00:00:00+00:00'},
                                                {'all': {'draw': 1,
                                                        'goals': {'against': 24,
                                                                'for': 7},
                                                        'lose': 12,
                                                        'played': 13,
                                                        'win': 0},
                                                'away': {'draw': 0,
                                                        'goals': {'against': 13,
                                                                'for': 3},
                                                        'lose': 6,
                                                        'played': 6,
                                                        'win': 0},
                                                'description': 'Relegation - '
                                                                'Championship',
                                                'form': 'LLLLL',
                                                'goalsDiff': -17,
                                                'group': 'Premier League',
                                                'home': {'draw': 1,
                                                        'goals': {'against': 11,
                                                                'for': 4},
                                                        'lose': 6,
                                                        'played': 7,
                                                        'win': 0},
                                                'points': 1,
                                                'rank': 20,
                                                'status': 'same',
                                                'team': {'id': 62,
                                                        'logo': 'https://media.api-sports.io/football/teams/62.png',
                                                        'name': 'Sheffield Utd'},
                                                'update': '2020-12-17T00:00:00+00:00'}]]}}],
        'results': 1}