 
top_scorers = {'errors': [],
                'get': 'players/topscorers',
                'paging': {'current': 0, 'total': 1},
                'parameters': {'league': '39', 'season': '2020'},
                'response': [{'player': {'age': 23,
                                        'birth': {'country': 'England',
                                                    'date': '1997-03-16',
                                                    'place': 'Sheffield'},
                                        'firstname': 'Dominic',
                                        'height': '187 cm',
                                        'id': 18766,
                                        'injured': False,
                                        'lastname': 'Calvert-Lewin',
                                        'name': 'D. Calvert-Lewin',
                                        'nationality': 'England',
                                        'photo': 'https://media.api-sports.io/football/players/18766.png',
                                        'weight': '71 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 1, 'yellowred': 0},
                                            'dribbles': {'attempts': 14,
                                                            'past': None,
                                                            'success': 6},
                                            'duels': {'total': 159, 'won': 80},
                                            'fouls': {'committed': 11, 'drawn': 16},
                                            'games': {'appearences': 11,
                                                        'captain': False,
                                                        'lineups': 11,
                                                        'minutes': 970,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.545454'},
                                            'goals': {'assists': None,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 11},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 14,
                                                        'key': 7,
                                                        'total': 215},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 0,
                                                        'won': None},
                                            'shots': {'on': 21, 'total': 31},
                                            'substitutes': {'bench': 0, 'in': 0, 'out': 2},
                                            'tackles': {'blocks': 3,
                                                        'interceptions': 2,
                                                        'total': 8},
                                            'team': {'id': 45,
                                                        'logo': 'https://media.api-sports.io/football/teams/45.png',
                                                        'name': 'Everton'}}]},
                            {'player': {'age': 28,
                                        'birth': {'country': 'Korea Republic',
                                                    'date': '1992-07-08',
                                                    'place': 'Chuncheon'},
                                        'firstname': 'Heung-Min',
                                        'height': '183 cm',
                                        'id': 186,
                                        'injured': False,
                                        'lastname': 'Son',
                                        'name': 'Son Heung-Min',
                                        'nationality': 'Korea Republic',
                                        'photo': 'https://media.api-sports.io/football/players/186.png',
                                        'weight': '78 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 0, 'yellowred': 0},
                                            'dribbles': {'attempts': 15,
                                                            'past': None,
                                                            'success': 8},
                                            'duels': {'total': 89, 'won': 36},
                                            'fouls': {'committed': 2, 'drawn': 15},
                                            'games': {'appearences': 11,
                                                        'captain': False,
                                                        'lineups': 11,
                                                        'minutes': 912,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.681818'},
                                            'goals': {'assists': 3,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 10},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 21,
                                                        'key': 20,
                                                        'total': 290},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 0,
                                                        'won': None},
                                            'shots': {'on': 13, 'total': 16},
                                            'substitutes': {'bench': 0, 'in': 0, 'out': 7},
                                            'tackles': {'blocks': 2,
                                                        'interceptions': 4,
                                                        'total': 7},
                                            'team': {'id': 47,
                                                        'logo': 'https://media.api-sports.io/football/teams/47.png',
                                                        'name': 'Tottenham'}}]},
                            {'player': {'age': 28,
                                        'birth': {'country': 'Egypt',
                                                    'date': '1992-06-15',
                                                    'place': 'Muḥāfaẓat al Gharbiyya'},
                                        'firstname': 'Mohamed',
                                        'height': '175 cm',
                                        'id': 306,
                                        'injured': False,
                                        'lastname': 'Salah Ghaly',
                                        'name': 'Mohamed Salah',
                                        'nationality': 'Egypt',
                                        'photo': 'https://media.api-sports.io/football/players/306.png',
                                        'weight': '71 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 0, 'yellowred': 0},
                                            'dribbles': {'attempts': 40,
                                                            'past': None,
                                                            'success': 17},
                                            'duels': {'total': 105, 'won': 35},
                                            'fouls': {'committed': 4, 'drawn': 10},
                                            'games': {'appearences': 10,
                                                        'captain': False,
                                                        'lineups': 10,
                                                        'minutes': 874,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.590000'},
                                            'goals': {'assists': 2,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 9},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 31,
                                                        'key': 23,
                                                        'total': 374},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 4,
                                                        'won': None},
                                            'shots': {'on': 17, 'total': 26},
                                            'substitutes': {'bench': 0, 'in': 0, 'out': 2},
                                            'tackles': {'blocks': None,
                                                        'interceptions': None,
                                                        'total': 6},
                                            'team': {'id': 40,
                                                        'logo': 'https://media.api-sports.io/football/teams/40.png',
                                                        'name': 'Liverpool'}}]},
                            {'player': {'age': 33,
                                        'birth': {'country': 'England',
                                                    'date': '1987-01-11',
                                                    'place': 'Sheffield'},
                                        'firstname': 'Jamie',
                                        'height': '179 cm',
                                        'id': 18788,
                                        'injured': False,
                                        'lastname': 'Vardy',
                                        'name': 'J. Vardy',
                                        'nationality': 'England',
                                        'photo': 'https://media.api-sports.io/football/players/18788.png',
                                        'weight': '74 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 1, 'yellowred': 0},
                                            'dribbles': {'attempts': 9,
                                                            'past': None,
                                                            'success': 7},
                                            'duels': {'total': 70, 'won': 31},
                                            'fouls': {'committed': 9, 'drawn': 8},
                                            'games': {'appearences': 10,
                                                        'captain': False,
                                                        'lineups': 9,
                                                        'minutes': 830,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.370000'},
                                            'goals': {'assists': 2,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 9},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 7,
                                                        'key': 7,
                                                        'total': 114},
                                            'penalty': {'commited': None,
                                                        'missed': 1,
                                                        'saved': None,
                                                        'scored': 5,
                                                        'won': None},
                                            'shots': {'on': 16, 'total': 21},
                                            'substitutes': {'bench': 1, 'in': 1, 'out': 2},
                                            'tackles': {'blocks': 1,
                                                        'interceptions': None,
                                                        'total': 5},
                                            'team': {'id': 46,
                                                        'logo': 'https://media.api-sports.io/football/teams/46.png',
                                                        'name': 'Leicester'}}]},
                            {'player': {'age': 27,
                                        'birth': {'country': 'England',
                                                    'date': '1993-09-05',
                                                    'place': 'Grantham'},
                                        'firstname': 'Patrick',
                                        'height': '185 cm',
                                        'id': 19134,
                                        'injured': False,
                                        'lastname': 'Bamford',
                                        'name': 'P. Bamford',
                                        'nationality': 'England',
                                        'photo': 'https://media.api-sports.io/football/players/19134.png',
                                        'weight': '71 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 1, 'yellowred': 0},
                                            'dribbles': {'attempts': 10,
                                                            'past': None,
                                                            'success': 6},
                                            'duels': {'total': 79, 'won': 28},
                                            'fouls': {'committed': 11, 'drawn': 5},
                                            'games': {'appearences': 11,
                                                        'captain': False,
                                                        'lineups': 11,
                                                        'minutes': 942,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.027272'},
                                            'goals': {'assists': 1,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 8},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 9,
                                                        'key': 6,
                                                        'total': 135},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 0,
                                                        'won': None},
                                            'shots': {'on': 19, 'total': 36},
                                            'substitutes': {'bench': 0, 'in': 0, 'out': 3},
                                            'tackles': {'blocks': 1,
                                                        'interceptions': None,
                                                        'total': 6},
                                            'team': {'id': 63,
                                                        'logo': 'https://media.api-sports.io/football/teams/63.png',
                                                        'name': 'Leeds'}}]},
                            {'player': {'age': 27,
                                        'birth': {'country': 'England',
                                                    'date': '1993-07-28',
                                                    'place': 'London'},
                                        'firstname': 'Harry',
                                        'height': '188 cm',
                                        'id': 184,
                                        'injured': False,
                                        'lastname': 'Kane',
                                        'name': 'H. Kane',
                                        'nationality': 'England',
                                        'photo': 'https://media.api-sports.io/football/players/184.png',
                                        'weight': '86 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 1, 'yellowred': 0},
                                            'dribbles': {'attempts': 21,
                                                            'past': None,
                                                            'success': 10},
                                            'duels': {'total': 154, 'won': 66},
                                            'fouls': {'committed': 15, 'drawn': 23},
                                            'games': {'appearences': 11,
                                                        'captain': False,
                                                        'lineups': 11,
                                                        'minutes': 984,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.990909'},
                                            'goals': {'assists': 10,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 8},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 17,
                                                        'key': 22,
                                                        'total': 269},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 2,
                                                        'won': None},
                                            'shots': {'on': 16, 'total': 32},
                                            'substitutes': {'bench': 0, 'in': 0, 'out': 1},
                                            'tackles': {'blocks': 4,
                                                        'interceptions': 3,
                                                        'total': 8},
                                            'team': {'id': 47,
                                                        'logo': 'https://media.api-sports.io/football/teams/47.png',
                                                        'name': 'Tottenham'}}]},
                            {'player': {'age': 28,
                                        'birth': {'country': "Côte d'Ivoire",
                                                    'date': '1992-11-10',
                                                    'place': 'Abidjan'},
                                        'firstname': 'Wilfried',
                                        'height': '180 cm',
                                        'id': 3247,
                                        'injured': False,
                                        'lastname': 'Zaha',
                                        'name': 'W. Zaha',
                                        'nationality': "Côte d'Ivoire",
                                        'photo': 'https://media.api-sports.io/football/players/3247.png',
                                        'weight': '66 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 2, 'yellowred': 0},
                                            'dribbles': {'attempts': 35,
                                                            'past': None,
                                                            'success': 16},
                                            'duels': {'total': 127, 'won': 53},
                                            'fouls': {'committed': 13, 'drawn': 28},
                                            'games': {'appearences': 9,
                                                        'captain': False,
                                                        'lineups': 9,
                                                        'minutes': 801,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.255555'},
                                            'goals': {'assists': 2,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 7},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 17,
                                                        'key': 13,
                                                        'total': 198},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 2,
                                                        'won': None},
                                            'shots': {'on': 9, 'total': 15},
                                            'substitutes': {'bench': 0, 'in': 0, 'out': 1},
                                            'tackles': {'blocks': None,
                                                        'interceptions': 2,
                                                        'total': 6},
                                            'team': {'id': 52,
                                                        'logo': 'https://media.api-sports.io/football/teams/52.png',
                                                        'name': 'Crystal Palace'}}]},
                            {'player': {'age': 26,
                                        'birth': {'country': 'Portugal',
                                                    'date': '1994-09-08',
                                                    'place': 'Maia'},
                                        'firstname': 'Bruno Miguel',
                                        'height': '173 cm',
                                        'id': 1485,
                                        'injured': False,
                                        'lastname': 'Borges Fernandes',
                                        'name': 'Bruno Fernandes',
                                        'nationality': 'Portugal',
                                        'photo': 'https://media.api-sports.io/football/players/1485.png',
                                        'weight': '80 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 2, 'yellowred': 0},
                                            'dribbles': {'attempts': 17,
                                                            'past': None,
                                                            'success': 7},
                                            'duels': {'total': 111, 'won': 44},
                                            'fouls': {'committed': 13, 'drawn': 15},
                                            'games': {'appearences': 10,
                                                        'captain': False,
                                                        'lineups': 9,
                                                        'minutes': 795,
                                                        'number': None,
                                                        'position': 'Midfielder',
                                                        'rating': '7.790000'},
                                            'goals': {'assists': 4,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 7},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 44,
                                                        'key': 35,
                                                        'total': 580},
                                            'penalty': {'commited': None,
                                                        'missed': 1,
                                                        'saved': None,
                                                        'scored': 3,
                                                        'won': None},
                                            'shots': {'on': 14, 'total': 21},
                                            'substitutes': {'bench': 1, 'in': 1, 'out': 2},
                                            'tackles': {'blocks': None,
                                                        'interceptions': 7,
                                                        'total': 19},
                                            'team': {'id': 33,
                                                        'logo': 'https://media.api-sports.io/football/teams/33.png',
                                                        'name': 'Manchester United'}}]},
                            {'player': {'age': 28,
                                        'birth': {'country': 'England',
                                                    'date': '1992-02-27',
                                                    'place': 'Coventry'},
                                        'firstname': 'Callum',
                                        'height': '180 cm',
                                        'id': 2939,
                                        'injured': False,
                                        'lastname': 'Wilson',
                                        'name': 'C. Wilson',
                                        'nationality': 'England',
                                        'photo': 'https://media.api-sports.io/football/players/2939.png',
                                        'weight': '66 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 1, 'yellowred': 0},
                                            'dribbles': {'attempts': 8,
                                                            'past': None,
                                                            'success': 6},
                                            'duels': {'total': 100, 'won': 38},
                                            'fouls': {'committed': 12, 'drawn': 13},
                                            'games': {'appearences': 9,
                                                        'captain': False,
                                                        'lineups': 9,
                                                        'minutes': 790,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.233333'},
                                            'goals': {'assists': 2,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 7},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 9,
                                                        'key': 8,
                                                        'total': 129},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 3,
                                                        'won': None},
                                            'shots': {'on': 8, 'total': 15},
                                            'substitutes': {'bench': 0, 'in': 0, 'out': 3},
                                            'tackles': {'blocks': 1,
                                                        'interceptions': 4,
                                                        'total': 3},
                                            'team': {'id': 34,
                                                        'logo': 'https://media.api-sports.io/football/teams/34.png',
                                                        'name': 'Newcastle'}}]},
                            {'player': {'age': 25,
                                        'birth': {'country': 'England',
                                                    'date': '1995-12-30',
                                                    'place': 'Torbay'},
                                        'firstname': 'Ollie',
                                        'height': '180 cm',
                                        'id': 19366,
                                        'injured': False,
                                        'lastname': 'Watkins',
                                        'name': 'O. Watkins',
                                        'nationality': 'England',
                                        'photo': 'https://media.api-sports.io/football/players/19366.png',
                                        'weight': '70 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 0, 'yellowred': 0},
                                            'dribbles': {'attempts': 15,
                                                            'past': None,
                                                            'success': 12},
                                            'duels': {'total': 138, 'won': 68},
                                            'fouls': {'committed': 7, 'drawn': 10},
                                            'games': {'appearences': 9,
                                                        'captain': False,
                                                        'lineups': 9,
                                                        'minutes': 810,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.233333'},
                                            'goals': {'assists': 1,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 6},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 15,
                                                        'key': 12,
                                                        'total': 203},
                                            'penalty': {'commited': None,
                                                        'missed': 1,
                                                        'saved': None,
                                                        'scored': 1,
                                                        'won': None},
                                            'shots': {'on': 9, 'total': 19},
                                            'substitutes': {'bench': 0, 'in': 0, 'out': 0},
                                            'tackles': {'blocks': None,
                                                        'interceptions': 5,
                                                        'total': 9},
                                            'team': {'id': 66,
                                                        'logo': 'https://media.api-sports.io/football/teams/66.png',
                                                        'name': 'Aston Villa'}}]},
                            {'player': {'age': 28,
                                        'birth': {'country': 'England',
                                                    'date': '1992-07-23',
                                                    'place': 'Winchester'},
                                        'firstname': 'Daniel William John',
                                        'height': '178 cm',
                                        'id': 18955,
                                        'injured': False,
                                        'lastname': 'Ings',
                                        'name': 'D. Ings',
                                        'nationality': 'England',
                                        'photo': 'https://media.api-sports.io/football/players/18955.png',
                                        'weight': '73 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 0, 'yellowred': 0},
                                            'dribbles': {'attempts': 21,
                                                            'past': None,
                                                            'success': 11},
                                            'duels': {'total': 79, 'won': 32},
                                            'fouls': {'committed': 6, 'drawn': 11},
                                            'games': {'appearences': 8,
                                                        'captain': False,
                                                        'lineups': 7,
                                                        'minutes': 669,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.375000'},
                                            'goals': {'assists': 2,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 6},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 12,
                                                        'key': 7,
                                                        'total': 163},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 2,
                                                        'won': None},
                                            'shots': {'on': 11, 'total': 15},
                                            'substitutes': {'bench': 1, 'in': 1, 'out': 1},
                                            'tackles': {'blocks': 1,
                                                        'interceptions': None,
                                                        'total': 5},
                                            'team': {'id': 41,
                                                        'logo': 'https://media.api-sports.io/football/teams/41.png',
                                                        'name': 'Southampton'}}]},
                            {'player': {'age': 25,
                                        'birth': {'country': 'England',
                                                    'date': '1995-09-10',
                                                    'place': 'Birmingham'},
                                        'firstname': 'Jack',
                                        'height': '175 cm',
                                        'id': 19187,
                                        'injured': False,
                                        'lastname': 'Grealish',
                                        'name': 'J. Grealish',
                                        'nationality': 'England',
                                        'photo': 'https://media.api-sports.io/football/players/19187.png',
                                        'weight': '68 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 2, 'yellowred': 0},
                                            'dribbles': {'attempts': 40,
                                                            'past': None,
                                                            'success': 29},
                                            'duels': {'total': 152, 'won': 95},
                                            'fouls': {'committed': 17, 'drawn': 40},
                                            'games': {'appearences': 9,
                                                        'captain': False,
                                                        'lineups': 9,
                                                        'minutes': 810,
                                                        'number': None,
                                                        'position': 'Midfielder',
                                                        'rating': '7.955555'},
                                            'goals': {'assists': 5,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 5},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 31,
                                                        'key': 27,
                                                        'total': 344},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 0,
                                                        'won': None},
                                            'shots': {'on': 11, 'total': 14},
                                            'substitutes': {'bench': 0, 'in': 0, 'out': 0},
                                            'tackles': {'blocks': None,
                                                        'interceptions': 4,
                                                        'total': 14},
                                            'team': {'id': 66,
                                                        'logo': 'https://media.api-sports.io/football/teams/66.png',
                                                        'name': 'Aston Villa'}}]},
                            {'player': {'age': 24,
                                        'birth': {'country': 'Portugal',
                                                    'date': '1996-12-04',
                                                    'place': 'Massarelos'},
                                        'firstname': 'Diogo José',
                                        'height': '178 cm',
                                        'id': 2678,
                                        'injured': False,
                                        'lastname': 'Teixeira da Silva',
                                        'name': 'Diogo Jota',
                                        'nationality': 'Portugal',
                                        'photo': 'https://media.api-sports.io/football/players/2678.png',
                                        'weight': '68 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 0, 'yellowred': 0},
                                            'dribbles': {'attempts': 19,
                                                            'past': None,
                                                            'success': 9},
                                            'duels': {'total': 83, 'won': 24},
                                            'fouls': {'committed': 11, 'drawn': 8},
                                            'games': {'appearences': 9,
                                                        'captain': False,
                                                        'lineups': 5,
                                                        'minutes': 501,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '6.900000'},
                                            'goals': {'assists': None,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 5},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 18,
                                                        'key': 6,
                                                        'total': 196},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 0,
                                                        'won': None},
                                            'shots': {'on': 11, 'total': 17},
                                            'substitutes': {'bench': 4, 'in': 4, 'out': 2},
                                            'tackles': {'blocks': None,
                                                        'interceptions': None,
                                                        'total': 3},
                                            'team': {'id': 40,
                                                        'logo': 'https://media.api-sports.io/football/teams/40.png',
                                                        'name': 'Liverpool'}}]},
                            {'player': {'age': 24,
                                        'birth': {'country': 'Germany',
                                                    'date': '1996-03-06',
                                                    'place': 'Stuttgart'},
                                        'firstname': 'Timo',
                                        'height': '180 cm',
                                        'id': 1166,
                                        'injured': False,
                                        'lastname': 'Werner',
                                        'name': 'T. Werner',
                                        'nationality': 'Germany',
                                        'photo': 'https://media.api-sports.io/football/players/1166.png',
                                        'weight': '75 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 0, 'yellowred': 0},
                                            'dribbles': {'attempts': 28,
                                                            'past': None,
                                                            'success': 13},
                                            'duels': {'total': 80, 'won': 32},
                                            'fouls': {'committed': 8, 'drawn': 10},
                                            'games': {'appearences': 11,
                                                        'captain': False,
                                                        'lineups': 11,
                                                        'minutes': 938,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.000000'},
                                            'goals': {'assists': 3,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 4},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 24,
                                                        'key': 10,
                                                        'total': 330},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 0,
                                                        'won': None},
                                            'shots': {'on': 14, 'total': 21},
                                            'substitutes': {'bench': 1, 'in': 0, 'out': 5},
                                            'tackles': {'blocks': None,
                                                        'interceptions': 5,
                                                        'total': 8},
                                            'team': {'id': 49,
                                                        'logo': 'https://media.api-sports.io/football/teams/49.png',
                                                        'name': 'Chelsea'}}]},
                            {'player': {'age': 26,
                                        'birth': {'country': 'England',
                                                    'date': '1994-11-01',
                                                    'place': 'Southampton'},
                                        'firstname': 'James',
                                        'height': '173 cm',
                                        'id': 2938,
                                        'injured': False,
                                        'lastname': 'Ward-Prowse',
                                        'name': 'J. Ward-Prowse',
                                        'nationality': 'England',
                                        'photo': 'https://media.api-sports.io/football/players/2938.png',
                                        'weight': '66 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 2, 'yellowred': 0},
                                            'dribbles': {'attempts': 5,
                                                            'past': None,
                                                            'success': 3},
                                            'duels': {'total': 110, 'won': 54},
                                            'fouls': {'committed': 19, 'drawn': 12},
                                            'games': {'appearences': 11,
                                                        'captain': False,
                                                        'lineups': 11,
                                                        'minutes': 990,
                                                        'number': None,
                                                        'position': 'Midfielder',
                                                        'rating': '7.436363'},
                                            'goals': {'assists': 3,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 4},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 55,
                                                        'key': 18,
                                                        'total': 709},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 0,
                                                        'won': None},
                                            'shots': {'on': 7, 'total': 10},
                                            'substitutes': {'bench': 0, 'in': 0, 'out': 0},
                                            'tackles': {'blocks': 2,
                                                        'interceptions': 14,
                                                        'total': 23},
                                            'team': {'id': 41,
                                                        'logo': 'https://media.api-sports.io/football/teams/41.png',
                                                        'name': 'Southampton'}}]},
                            {'player': {'age': 24,
                                        'birth': {'country': 'England',
                                                    'date': '1996-12-20',
                                                    'place': 'Leominster'},
                                        'firstname': 'Jarrod',
                                        'height': None,
                                        'id': 19428,
                                        'injured': False,
                                        'lastname': 'Bowen',
                                        'name': 'J. Bowen',
                                        'nationality': 'England',
                                        'photo': 'https://media.api-sports.io/football/players/19428.png',
                                        'weight': None},
                            'statistics': [{'cards': {'red': 0, 'yellow': 0, 'yellowred': 0},
                                            'dribbles': {'attempts': 20,
                                                            'past': None,
                                                            'success': 10},
                                            'duels': {'total': 86, 'won': 35},
                                            'fouls': {'committed': 6, 'drawn': 13},
                                            'games': {'appearences': 11,
                                                        'captain': False,
                                                        'lineups': 11,
                                                        'minutes': 913,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.072727'},
                                            'goals': {'assists': 1,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 4},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 16,
                                                        'key': 10,
                                                        'total': 232},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 0,
                                                        'won': None},
                                            'shots': {'on': 5, 'total': 13},
                                            'substitutes': {'bench': 0, 'in': 0, 'out': 10},
                                            'tackles': {'blocks': 1,
                                                        'interceptions': 5,
                                                        'total': 9},
                                            'team': {'id': 48,
                                                        'logo': 'https://media.api-sports.io/football/teams/48.png',
                                                        'name': 'West Ham'}}]},
                            {'player': {'age': 28,
                                        'birth': {'country': 'Senegal',
                                                    'date': '1992-04-10',
                                                    'place': 'Sedhiou'},
                                        'firstname': 'Sadio',
                                        'height': '175 cm',
                                        'id': 304,
                                        'injured': False,
                                        'lastname': 'Mané',
                                        'name': 'S. Mané',
                                        'nationality': 'Senegal',
                                        'photo': 'https://media.api-sports.io/football/players/304.png',
                                        'weight': '69 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 2, 'yellowred': 0},
                                            'dribbles': {'attempts': 38,
                                                            'past': None,
                                                            'success': 25},
                                            'duels': {'total': 158, 'won': 87},
                                            'fouls': {'committed': 19, 'drawn': 32},
                                            'games': {'appearences': 10,
                                                        'captain': False,
                                                        'lineups': 9,
                                                        'minutes': 825,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.280000'},
                                            'goals': {'assists': 1,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 4},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 23,
                                                        'key': 15,
                                                        'total': 295},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 0,
                                                        'won': None},
                                            'shots': {'on': 15, 'total': 26},
                                            'substitutes': {'bench': 1, 'in': 1, 'out': 2},
                                            'tackles': {'blocks': None,
                                                        'interceptions': 4,
                                                        'total': 14},
                                            'team': {'id': 40,
                                                        'logo': 'https://media.api-sports.io/football/teams/40.png',
                                                        'name': 'Liverpool'}}]},
                            {'player': {'age': 29,
                                        'birth': {'country': 'France',
                                                    'date': '1991-02-21',
                                                    'place': 'Sarcelles'},
                                        'firstname': 'Riyad',
                                        'height': '179 cm',
                                        'id': 635,
                                        'injured': False,
                                        'lastname': 'Mahrez',
                                        'name': 'R. Mahrez',
                                        'nationality': 'Algeria',
                                        'photo': 'https://media.api-sports.io/football/players/635.png',
                                        'weight': '67 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 0, 'yellowred': 0},
                                            'dribbles': {'attempts': 31,
                                                            'past': None,
                                                            'success': 17},
                                            'duels': {'total': 91, 'won': 37},
                                            'fouls': {'committed': 8, 'drawn': 8},
                                            'games': {'appearences': 8,
                                                        'captain': False,
                                                        'lineups': 8,
                                                        'minutes': 684,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '7.662500'},
                                            'goals': {'assists': 1,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 4},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 38,
                                                        'key': 23,
                                                        'total': 360},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 0,
                                                        'won': None},
                                            'shots': {'on': 10, 'total': 18},
                                            'substitutes': {'bench': 1, 'in': 0, 'out': 3},
                                            'tackles': {'blocks': None,
                                                        'interceptions': 1,
                                                        'total': 6},
                                            'team': {'id': 50,
                                                        'logo': 'https://media.api-sports.io/football/teams/50.png',
                                                        'name': 'Manchester City'}}]},
                            {'player': {'age': 29,
                                        'birth': {'country': 'Mexico',
                                                    'date': '1991-05-05',
                                                    'place': 'Tepeji del Río Ocampo'},
                                        'firstname': 'Raúl Alonso',
                                        'height': '187 cm',
                                        'id': 2887,
                                        'injured': False,
                                        'lastname': 'Jiménez Rodríguez',
                                        'name': 'R. Jiménez',
                                        'nationality': 'Mexico',
                                        'photo': 'https://media.api-sports.io/football/players/2887.png',
                                        'weight': '76 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 0, 'yellowred': 0},
                                            'dribbles': {'attempts': 21,
                                                            'past': None,
                                                            'success': 10},
                                            'duels': {'total': 107, 'won': 44},
                                            'fouls': {'committed': 9, 'drawn': 17},
                                            'games': {'appearences': 10,
                                                        'captain': False,
                                                        'lineups': 10,
                                                        'minutes': 825,
                                                        'number': None,
                                                        'position': 'Attacker',
                                                        'rating': '6.970000'},
                                            'goals': {'assists': None,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 4},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 20,
                                                        'key': 5,
                                                        'total': 259},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 0,
                                                        'won': None},
                                            'shots': {'on': 10, 'total': 22},
                                            'substitutes': {'bench': 0, 'in': 0, 'out': 2},
                                            'tackles': {'blocks': None,
                                                        'interceptions': 8,
                                                        'total': 3},
                                            'team': {'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/teams/39.png',
                                                        'name': 'Wolves'}}]},
                            {'player': {'age': 26,
                                        'birth': {'country': 'France',
                                                    'date': '1994-10-27',
                                                    'place': 'Lyon'},
                                        'firstname': 'Kurt Happy',
                                        'height': '190 cm',
                                        'id': 2726,
                                        'injured': False,
                                        'lastname': 'Zouma',
                                        'name': 'K. Zouma',
                                        'nationality': 'France',
                                        'photo': 'https://media.api-sports.io/football/players/2726.png',
                                        'weight': '96 kg'},
                            'statistics': [{'cards': {'red': 0, 'yellow': 1, 'yellowred': 0},
                                            'dribbles': {'attempts': None,
                                                            'past': None,
                                                            'success': None},
                                            'duels': {'total': 61, 'won': 39},
                                            'fouls': {'committed': 9, 'drawn': 1},
                                            'games': {'appearences': 10,
                                                        'captain': False,
                                                        'lineups': 10,
                                                        'minutes': 900,
                                                        'number': None,
                                                        'position': 'Defender',
                                                        'rating': '7.400000'},
                                            'goals': {'assists': None,
                                                        'conceded': 0,
                                                        'saves': None,
                                                        'total': 4},
                                            'league': {'country': 'England',
                                                        'flag': 'https://media.api-sports.io/flags/gb.svg',
                                                        'id': 39,
                                                        'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                                        'name': 'Premier League',
                                                        'season': 2020},
                                            'passes': {'accuracy': 68,
                                                        'key': 1,
                                                        'total': 752},
                                            'penalty': {'commited': None,
                                                        'missed': 0,
                                                        'saved': None,
                                                        'scored': 0,
                                                        'won': None},
                                            'shots': {'on': 6, 'total': 8},
                                            'substitutes': {'bench': 0, 'in': 0, 'out': 0},
                                            'tackles': {'blocks': 4,
                                                        'interceptions': 12,
                                                        'total': 4},
                                            'team': {'id': 49,
                                                        'logo': 'https://media.api-sports.io/football/teams/49.png',
                                                        'name': 'Chelsea'}}]}],
                'results': 20}