upcoming_onegame = {'errors': [],
        'get': 'fixtures',
        'paging': {'current': 1, 'total': 1},
        'parameters': {'id': '592345'},
        'response': [{'events': [],
                    'fixture': {'date': '2021-01-30T12:30:00+00:00',
                                'id': 592345,
                                'periods': {'first': None, 'second': None},
                                'referee': None,
                                'status': {'elapsed': None,
                                            'long': 'Not Started',
                                            'short': 'NS'},
                                'timestamp': 1612009800,
                                'timezone': 'UTC',
                                'venue': {'city': 'Liverpool',
                                            'id': 8560,
                                            'name': 'Goodison Park'}},
                    'goals': {'away': None, 'home': None},
                    'league': {'country': 'England',
                                'flag': 'https://media.api-sports.io/flags/gb.svg',
                                'id': 39,
                                'logo': 'https://media.api-sports.io/football/leagues/39.png',
                                'name': 'Premier League',
                                'round': 'Regular Season - 21',
                                'season': 2020},
                    'lineups': [],
                    'players': [],
                    'score': {'extratime': {'away': None, 'home': None},
                                'fulltime': {'away': None, 'home': None},
                                'halftime': {'away': None, 'home': None},
                                'penalty': {'away': None, 'home': None}},
                    'statistics': [],
                    'teams': {'away': {'id': 34,
                                        'logo': 'https://media.api-sports.io/football/teams/34.png',
                                        'name': 'Newcastle',
                                        'winner': None},
                                'home': {'id': 45,
                                        'logo': 'https://media.api-sports.io/football/teams/45.png',
                                        'name': 'Everton',
                                        'winner': None}}}],
        'results': 1}